language: node_js

node_js:
- '8'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
env:
  - CXX=g++-4.8
cache:
  directories:
  - node_modules

before_script:
  - npm run serve &

script:
  - npm run build:ci
  - npm run test:ci
